#include <iostream> 
#include <windows.h> 

using namespace std;

int main(int argc, char const *argv[])
{
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *--------* ------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                       --------------------" << endl;
    cout << "                          --------------" << endl;
    cout << "                              |     |   " << endl;
    cout << "                          ---------------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                   ---------------------------" << endl;
    cout << "                   ---------------------------" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;

    Sleep(1000);

    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;


    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *--------* ------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                       --------------------" << "        OK. But in Heinsight i am very powerfull" << endl;
    cout << "                          --------------" << endl;
    cout << "                              |     |   " << endl;
    cout << "                          ---------------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                   ---------------------------     -----" << endl;
    cout << "                   ---------------------------    -----" << endl;
    cout << "                   ---- ---------------- -----   -----" << endl;
    cout << "                   ---- ---------------- -----  -----" << endl;
    cout << "                   ---- ---------------- ----- -----" << endl;
    cout << "                   ---- ---------------- ----------" << endl;
    cout << "                   ---- ----------------   ----" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;

    Sleep(2000);

    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     -----* --------* ------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                       --------------------" << endl;
    cout << "                          --------------" << endl;
    cout << "                              |     |   " << endl;
    cout << "                          ---------------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                   ---------------------------" << endl;
    cout << "                   ---------------------------" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;

    Sleep(1000);

    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;


    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *--------* ------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                       --------------------" << "        You Just can't tell." << endl;
    cout << "                          --------------" << endl;
    cout << "                              |     |   " << endl;
    cout << "                          ---------------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                   ---------------------------     -----" << endl;
    cout << "                   ---------------------------    -----" << endl;
    cout << "                   ---- ---------------- -----   -----" << endl;
    cout << "                   ---- ---------------- -----  -----" << endl;
    cout << "                   ---- ---------------- ----- -----" << endl;
    cout << "                   ---- ---------------- ----------" << endl;
    cout << "                   ---- ----------------   ----" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;

    Sleep(2000);

    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;

     cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *--------* ------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                       --------------------" << "        ok... NOW I SHALL USE MY LAST RESORT PATHETIC HUMAN." << endl;
    cout << "                          --------------" << endl;
    cout << "                              |     |   " << endl;
    cout << "                          ---------------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                   ---------------------------" << endl;
    cout << "                   ---------------------------" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;

    Sleep(2000);


    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;


    cout << "                          -------------           -----" << endl;
    cout << "                       -------------------       -----" << endl;
    cout << "                     -----  --------  ------    -----" << endl;
    cout << "                     ----- *-------- *------   -----" << endl;
    cout << "                     -----------------------  -----         BEHOLD MY OTHER OTHER POWER!" << endl;
    cout << "                       --------------------  -----" << endl;
    cout << "                          --------------    -----" << endl;
    cout << "                              |     |      -----" << endl;
    cout << "                          --------------- -----" << endl;
    cout << "                     -------------------------" << endl;
    cout << "                   -------------------------" << endl;
    cout << "                   ------------------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;

    Sleep(2000);
    
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;


    cout << "                          -------------           -----" << endl;
    cout << "                       -------------------       -----" << endl;
    cout << "                     ----- *-------- *------    -----" << endl;
    cout << "                     -----  --------  ------   -----" << endl;
    cout << "                     -----------------------  -----         START COMMAND (SHUTDOWN /s /t 0)" << endl;
    cout << "                       --------------------  -----" << endl;
    cout << "                          --------------    -----" << endl;
    cout << "                              |     |      -----" << endl;
    cout << "                          --------------- -----" << endl;
    cout << "                     -------------------------" << endl;
    cout << "                   -------------------------" << endl;
    cout << "                   ------------------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;

    Sleep(2000);
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    Sleep(2000);

    cout << "*Windows Is Kindly Shutting down this program for you*";
    Sleep(3000);
    system("shutdown /s /t 0");

    
    return 0;
}
