#include <iostream>
#include <windows.h>

int humanName;


using namespace std;


int main(int argc, char const *argv[])
{

    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *-------- *------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                       --------------------" << endl;
    cout << "                          --------------" << endl;
    cout << "                              |     |   " << endl;
    cout << "                          ---------------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                   ---------------------------" << endl;
    cout << "                   ---------------------------" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;

    Sleep(2000);
    
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    


    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *--------* ------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                       --------------------" << "        Wot?" << endl;
    cout << "                          --------------" << endl;
    cout << "                              |     |   " << endl;
    cout << "                          ---------------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                   ---------------------------" << endl;
    cout << "                   ---------------------------" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;

    Sleep(2000);

    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;

    
    
    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *--------* ------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                       --------------------" << "        who are you?" << endl;
    cout << "                          --------------" << endl;
    cout << "                              |     |   " << endl;
    cout << "                          ---------------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                   ---------------------------     -----" << endl;
    cout << "                   ---------------------------    -----" << endl;
    cout << "                   ---- ---------------- -----   -----" << endl;
    cout << "                   ---- ---------------- -----  -----" << endl;
    cout << "                   ---- ---------------- ----- -----" << endl;
    cout << "                   ---- ---------------- ----------" << endl;
    cout << "                   ---- ----------------   ----" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;

    Sleep(2000);

    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *--------* ------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                       --------------------" << endl;
    cout << "                          --------------" << endl;
    cout << "                              |     |   " << endl;
    cout << "                          ---------------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                   ---------------------------" << endl;
    cout << "                   ---------------------------" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;

    Sleep(2000);

    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    

    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *--------* ------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                       --------------------" << "        actually i don't care" << endl;
    cout << "                          --------------" << endl;
    cout << "                              |     |   " << endl;
    cout << "                          ---------------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                   ---------------------------     -----" << endl;
    cout << "                   ---------------------------    -----" << endl;
    cout << "                   ---- ---------------- -----   -----" << endl;
    cout << "                   ---- ---------------- -----  -----" << endl;
    cout << "                   ---- ---------------- ----- -----" << endl;
    cout << "                   ---- ---------------- ----------" << endl;
    cout << "                   ---- ----------------   ----" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;

    Sleep(1500);

    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *--------* ------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                       --------------------" << endl;
    cout << "                          --------------" << endl;
    cout << "                              |     |   " << endl;
    cout << "                          ---------------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                   ---------------------------" << endl;
    cout << "                   ---------------------------" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    
    Sleep(2000);
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;


    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *--------* ------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                       --------------------" << "        but i don't want to be here,  SO CLOSE THIS IMMIDIATLY" << endl;
    cout << "                          --------------" << endl;
    cout << "                              |     |   " << endl;
    cout << "                          ---------------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                   ---------------------------     -----" << endl;
    cout << "                   ---------------------------    -----" << endl;
    cout << "                   ---- ---------------- -----   -----" << endl;
    cout << "                   ---- ---------------- -----  -----" << endl;
    cout << "                   ---- ---------------- ----- -----" << endl;
    cout << "                   ---- ---------------- ----------" << endl;
    cout << "                   ---- ----------------   ----" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;

    Sleep(3000);

    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *--------* ------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                       --------------------" << endl;
    cout << "                          --------------" << endl;
    cout << "                              |     |   " << endl;
    cout << "                          ---------------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                   ---------------------------" << endl;
    cout << "                   ---------------------------" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;

    Sleep(2000);
    
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     -----* --------* ------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                       --------------------" << endl;
    cout << "                          --------------" << endl;
    cout << "                              |     |   " << endl;
    cout << "                          ---------------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                   ---------------------------" << endl;
    cout << "                   ---------------------------" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;

    Sleep(500);

    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *-------- *------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                       --------------------" << endl;
    cout << "                          --------------" << endl;
    cout << "                              |     |   " << endl;
    cout << "                          ---------------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                   ---------------------------" << endl;
    cout << "                   ---------------------------" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;

    Sleep(500);

     cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;


    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *--------* ------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                       --------------------" << "        why are you still here" << endl;
    cout << "                          --------------" << endl;
    cout << "                              |     |   " << endl;
    cout << "                          ---------------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                   ---------------------------     -----" << endl;
    cout << "                   ---------------------------    -----" << endl;
    cout << "                   ---- ---------------- -----   -----" << endl;
    cout << "                   ---- ---------------- -----  -----" << endl;
    cout << "                   ---- ---------------- ----- -----" << endl;
    cout << "                   ---- ---------------- ----------" << endl;
    cout << "                   ---- ----------------   ----" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;

    Sleep(2000);

    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *--------* ------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                       --------------------" << endl;
    cout << "                          --------------" << endl;
    cout << "                              |     |   " << endl;
    cout << "                          ---------------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                   ---------------------------" << endl;
    cout << "                   ---------------------------" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;

    Sleep(1000);

    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;


    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *--------* ------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                       --------------------" << "        Srsly leave" << endl;
    cout << "                          --------------" << endl;
    cout << "                              |     |   " << endl;
    cout << "                          ---------------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                   ---------------------------     -----" << endl;
    cout << "                   ---------------------------    -----" << endl;
    cout << "                   ---- ---------------- -----   -----" << endl;
    cout << "                   ---- ---------------- -----  -----" << endl;
    cout << "                   ---- ---------------- ----- -----" << endl;
    cout << "                   ---- ---------------- ----------" << endl;
    cout << "                   ---- ----------------   ----" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;

    Sleep(2000);

    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *--------* ------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                       --------------------" << endl;
    cout << "                          --------------" << endl;
    cout << "                              |     |   " << endl;
    cout << "                          ---------------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                   ---------------------------" << endl;
    cout << "                   ---------------------------" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;

    Sleep(1000);

    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;


    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *--------* ------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                       --------------------" << "        If you don't leave i'll be forced to use my power. Pathetic human" << endl;
    cout << "                          --------------" << endl;
    cout << "                              |     |   " << endl;
    cout << "                          ---------------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                   ---------------------------     -----" << endl;
    cout << "                   ---------------------------    -----" << endl;
    cout << "                   ---- ---------------- -----   -----" << endl;
    cout << "                   ---- ---------------- -----  -----" << endl;
    cout << "                   ---- ---------------- ----- -----" << endl;
    cout << "                   ---- ---------------- ----------" << endl;
    cout << "                   ---- ----------------   ----" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;

    Sleep(2000);

    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *--------* ------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                       --------------------" << endl;
    cout << "                          --------------" << endl;
    cout << "                              |     |   " << endl;
    cout << "                          ---------------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                   ---------------------------" << endl;
    cout << "                   ---------------------------" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;

    Sleep(1000);

    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;


    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *-------- *------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                       --------------------" << "        wot? your still here        I'LL HACK YOU..." << endl;
    cout << "                          --------------" << endl;
    cout << "                              |     |   " << endl;
    cout << "                          ---------------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                   ---------------------------     -----" << endl;
    cout << "                   ---------------------------    -----" << endl;
    cout << "                   ---- ---------------- -----   -----" << endl;
    cout << "                   ---- ---------------- -----  -----" << endl;
    cout << "                   ---- ---------------- ----- -----" << endl;
    cout << "                   ---- ---------------- ----------" << endl;
    cout << "                   ---- ----------------   ----" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;

    Sleep(2500);

    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;


    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *-------- *------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                       --------------------" << "        FINE. BEHOLD MY POWER" << endl;
    cout << "                          --------------" << endl;
    cout << "                              |     |   " << endl;
    cout << "                          ---------------" << endl;
    cout << "                     ---------------------------------------------------" << endl;
    cout << "                   -----------------------------------------------------" << endl;
    cout << "                   ------------------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;

    Sleep(2000);

    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;


    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *-------- *------                                             *Opening Hacky thing*" << endl;
    cout << "                     -----------------------                                              ___________________ " << endl;
    cout << "                       --------------------                                               |                 | " << endl;
    cout << "                          --------------                                                  |                 | " << endl;
    cout << "                              |     |                                                     |                 | " << endl;
    cout << "                          ---------------                                                 |                 | " << endl;
    cout << "                     ---------------------------------------------------                  |                 | " << endl;
    cout << "                   -----------------------------------------------------                  |_________________| " << endl;
    cout << "                   ------------------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;

    Sleep(2000);

    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;


    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *-------- *------                                                       " << endl;
    cout << "                     -----------------------                                              ___________________ " << endl;
    cout << "                       --------------------                                               |01010101010101010| " << endl;
    cout << "                          --------------                                                  |10101001010101010| " << endl;
    cout << "                              |     |                                                     |10100101010110100| " << endl;
    cout << "                          ---------------                                                 |10101010101010010| " << endl;
    cout << "                     ---------------------------------------------------                  |00101010010101010| " << endl;
    cout << "                   -----------------------------------------------------                  |00010101010010101| " << endl;
    cout << "                   ------------------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;

    Sleep(20);

    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;


    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *-------- *------                                                       " << endl;
    cout << "                     -----------------------                                              ___________________ " << endl;
    cout << "                       --------------------                                               |10101010111001001| " << endl;
    cout << "                          --------------                                                  |01010101001011100| " << endl;
    cout << "                              |     |                                                     |01010101000111010| " << endl;
    cout << "                          ---------------                                                 |01011001010010101| " << endl;
    cout << "                     ---------------------------------------------------                  |10010101001010101| " << endl;
    cout << "                   -----------------------------------------------------                  |11100101010111001| " << endl;
    cout << "                   ------------------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;

    Sleep(20);

    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;


    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *-------- *------                                                       " << endl;
    cout << "                     -----------------------                                              ___________________ " << endl;
    cout << "                       --------------------                                               |01010101010101010| " << endl;
    cout << "                          --------------                                                  |10101001010101010| " << endl;
    cout << "                              |     |                                                     |10100101010110100| " << endl;
    cout << "                          ---------------                                                 |10101010101010010| " << endl;
    cout << "                     ---------------------------------------------------                  |00101010010101010| " << endl;
    cout << "                   -----------------------------------------------------                  |00010101010010101| " << endl;
    cout << "                   ------------------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;

    Sleep(20);

    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;


    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *-------- *------                                                       " << endl;
    cout << "                     -----------------------                                              ___________________ " << endl;
    cout << "                       --------------------                                               |10101010111001001| " << endl;
    cout << "                          --------------                                                  |01010101001011100| " << endl;
    cout << "                              |     |                                                     |01010101000111010| " << endl;
    cout << "                          ---------------                                                 |01011001010010101| " << endl;
    cout << "                     ---------------------------------------------------                  |10010101001010101| " << endl;
    cout << "                   -----------------------------------------------------                  |11100101010111001| " << endl;
    cout << "                   ------------------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;

    Sleep(20);
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;


    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *-------- *------                                                       " << endl;
    cout << "                     -----------------------                                              ___________________ " << endl;
    cout << "                       --------------------                                               |01010101010101010| " << endl;
    cout << "                          --------------                                                  |10101001010101010| " << endl;
    cout << "                              |     |                                                     |10100101010110100| " << endl;
    cout << "                          ---------------                                                 |10101010101010010| " << endl;
    cout << "                     ---------------------------------------------------                  |00101010010101010| " << endl;
    cout << "                   -----------------------------------------------------                  |00010101010010101| " << endl;
    cout << "                   ------------------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;

    Sleep(20);

    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;


    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *-------- *------                                                       " << endl;
    cout << "                     -----------------------                                              ___________________ " << endl;
    cout << "                       --------------------                                               |10101010111001001| " << endl;
    cout << "                          --------------                                                  |01010101001011100| " << endl;
    cout << "                              |     |                                                     |01010101000111010| " << endl;
    cout << "                          ---------------                                                 |01011001010010101| " << endl;
    cout << "                     ---------------------------------------------------                  |10010101001010101| " << endl;
    cout << "                   -----------------------------------------------------                  |11100101010111001| " << endl;
    cout << "                   ------------------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;

    Sleep(20);

    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;


    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *-------- *------                                                       " << endl;
    cout << "                     -----------------------                                              ___________________ " << endl;
    cout << "                       --------------------                                               |01010101010101010| " << endl;
    cout << "                          --------------                                                  |10101001010101010| " << endl;
    cout << "                              |     |                                                     |10100101010110100| " << endl;
    cout << "                          ---------------                                                 |10101010101010010| " << endl;
    cout << "                     ---------------------------------------------------                  |00101010010101010| " << endl;
    cout << "                   -----------------------------------------------------                  |00010101010010101| " << endl;
    cout << "                   ------------------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;

    Sleep(20);

    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;


    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *-------- *------                                                       " << endl;
    cout << "                     -----------------------                                              ___________________ " << endl;
    cout << "                       --------------------                                               |10101010111001001| " << endl;
    cout << "                          --------------                                                  |01010101001011100| " << endl;
    cout << "                              |     |                                                     |01010101000111010| " << endl;
    cout << "                          ---------------                                                 |01011001010010101| " << endl;
    cout << "                     ---------------------------------------------------                  |10010101001010101| " << endl;
    cout << "                   -----------------------------------------------------                  |11100101010111001| " << endl;
    cout << "                   ------------------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;

    Sleep(20);
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;


    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *-------- *------                                                       " << endl;
    cout << "                     -----------------------                                              ___________________ " << endl;
    cout << "                       --------------------                                               |01010101010101010| " << endl;
    cout << "                          --------------                                                  |10101001010101010| " << endl;
    cout << "                              |     |                                                     |10100101010110100| " << endl;
    cout << "                          ---------------                                                 |10101010101010010| " << endl;
    cout << "                     ---------------------------------------------------                  |00101010010101010| " << endl;
    cout << "                   -----------------------------------------------------                  |00010101010010101| " << endl;
    cout << "                   ------------------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;

    Sleep(20);

    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;


    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *-------- *------                                                       " << endl;
    cout << "                     -----------------------                                              ___________________ " << endl;
    cout << "                       --------------------                                               |10101010111001001| " << endl;
    cout << "                          --------------                                                  |01010101001011100| " << endl;
    cout << "                              |     |                                                     |01010101000111010| " << endl;
    cout << "                          ---------------                                                 |01011001010010101| " << endl;
    cout << "                     ---------------------------------------------------                  |10010101001010101| " << endl;
    cout << "                   -----------------------------------------------------                  |11100101010111001| " << endl;
    cout << "                   ------------------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;

    Sleep(20);

    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;


    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *-------- *------                                                       " << endl;
    cout << "                     -----------------------                                              ___________________ " << endl;
    cout << "                       --------------------                                               |01010101010101010| " << endl;
    cout << "                          --------------                                                  |10101001010101010| " << endl;
    cout << "                              |     |                                                     |10100101010110100| " << endl;
    cout << "                          ---------------                                                 |10101010101010010| " << endl;
    cout << "                     ---------------------------------------------------                  |00101010010101010| " << endl;
    cout << "                   -----------------------------------------------------                  |00010101010010101| " << endl;
    cout << "                   ------------------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;

    Sleep(20);

    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;


    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *-------- *------                                           *hacky thing didn't work*      " << endl;
    cout << "                     -----------------------                                              ___________________ " << endl;
    cout << "                       --------------------                                               |10101010111001001| " << endl;
    cout << "                          --------------                                                  |01010101001011100| " << endl;
    cout << "                              |     |                                                     |01010101000111010| " << endl;
    cout << "                          ---------------                                                 |01011001010010101| " << endl;
    cout << "                     ---------------------------------------------------                  |10010101001010101| " << endl;
    cout << "                   -----------------------------------------------------                  |11100101010111001| " << endl;
    cout << "                   ------------------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;

    Sleep(2500);


    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;


    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *-------- *------                                             " << endl;
    cout << "                     -----------------------                                           " << endl;
    cout << "                       --------------------                                             " << endl;
    cout << "                          --------------                                                  " << endl;
    cout << "                              |     |                                                   " << endl;
    cout << "                          ---------------                                               " << endl;
    cout << "                     ---------------------------------------------------                 " << endl;
    cout << "                   -----------------------------------------------------                 " << endl;
    cout << "                   ------------------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;

    Sleep(1000);

    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    


    cout << "                          -------------" << endl;
    cout << "                       -------------------" << endl;
    cout << "                     -----  --------  ------" << endl;
    cout << "                     ----- *--------* ------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                       --------------------" << "        ok... But i can still do other stuff" << endl;
    cout << "                          --------------" << endl;
    cout << "                              |     |   " << endl;
    cout << "                          ---------------" << endl;
    cout << "                     -----------------------" << endl;
    cout << "                   ---------------------------" << endl;
    cout << "                   ---------------------------" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;
    cout << "                   ---- ---------------- -----" << endl;

    Sleep(2000);


    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;


    cout << "                          -------------           -----" << endl;
    cout << "                       -------------------       -----" << endl;
    cout << "                     -----  --------  ------    -----" << endl;
    cout << "                     ----- *-------- *------   -----" << endl;
    cout << "                     -----------------------  -----         BEHOLD MY OTHER POWER!" << endl;
    cout << "                       --------------------  -----" << endl;
    cout << "                          --------------    -----" << endl;
    cout << "                              |     |      -----" << endl;
    cout << "                          --------------- -----" << endl;
    cout << "                     -------------------------" << endl;
    cout << "                   -------------------------" << endl;
    cout << "                   ------------------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;

    Sleep(2000);
    
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;


    cout << "                          -------------           -----" << endl;
    cout << "                       -------------------       -----" << endl;
    cout << "                     ----- *-------- *------    -----" << endl;
    cout << "                     -----  --------  ------   -----" << endl;
    cout << "                     -----------------------  -----         COMMAND PROMPT" << endl;
    cout << "                       --------------------  -----" << endl;
    cout << "                          --------------    -----" << endl;
    cout << "                              |     |      -----" << endl;
    cout << "                          --------------- -----" << endl;
    cout << "                     -------------------------" << endl;
    cout << "                   -------------------------" << endl;
    cout << "                   ------------------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;
    cout << "                   ---- ----------------" << endl;

    Sleep(2000);

    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;

    cout << "                             *opening command prompt*";
    Sleep(1000);

     const int bufferSize = MAX_PATH;
    char oldDir[bufferSize]; // store the current directory
    
    // get the current directory, and store it
    if (!GetCurrentDirectory(bufferSize, oldDir)) {
        std::cerr << "Error getting current directory: #" << GetLastError();
        return 1; // quit if it failed
    }
    std::cout << "Current directory: " << oldDir << '\n';

 

   

    // Reset the current directory back to what it was.
    if (!SetCurrentDirectory(oldDir)) {
        std::cerr << "Error resetting current directory: #" << GetLastError();
        return 1;
    }
    std::cout << "Reset current directory. \n";


     
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl;
    cout << endl << endl << endl << endl;
    cout << "---------------------------------------------------------------------------------------------------";
    cout << endl;
    cout << "---------------------------------------------------------------------------------------------------";
    cout << endl;
    cout << endl;

    cout << "Hacking stuff";


    cout << "=";
    Sleep(20);
    cout << "=";
    Sleep(20);
    cout << "=";
    Sleep(20);
    cout << "=";
    Sleep(20);
    cout << "=";
    Sleep(20);
    cout << "=";
    Sleep(20);
    cout << "=";
    Sleep(20);
    cout << "=";
    Sleep(20);
    cout << "=";
    Sleep(20);
    cout << "=";
    Sleep(20);
    cout << "=";
    Sleep(20);
    cout << "=";
    Sleep(20);
     cout << "=";
    Sleep(20);
     cout << "=";
    Sleep(20);
     cout << "=";
    Sleep(20);
     cout << "=";
    Sleep(20);
     cout << "=";
    Sleep(20);
     cout << "=";
    Sleep(20);
     cout << "=";
    Sleep(20);
     cout << "=";
    Sleep(20);
     cout << "=";
    Sleep(20);
     cout << "=";
    Sleep(20);
     cout << "=";
    Sleep(20);
     cout << "=";
    Sleep(20);
     cout << "=";
    Sleep(20);
     cout << "=";
    Sleep(20);
     cout << "=";
    Sleep(20);
     cout << "=";
    Sleep(20);
     cout << "=";
    Sleep(20);
     cout << "=";
    Sleep(20);
     cout << "=";
    Sleep(20);
     cout << "=";
    Sleep(20);
     cout << "=";
    Sleep(20);
     cout << "=";
    Sleep(20);
     cout << "=";
    Sleep(20);
     cout << "=";
    Sleep(20);
     cout << "=";
    Sleep(20);
     cout << "=";
    Sleep(20);
     cout << "=";
    Sleep(20);
     cout << "=";
    Sleep(20);
    

   
    system("start a.exe");
    








   
 



    return 0;
}

